import Head from "next/head";
import { Manrope } from "next/font/google";
import { Alert, Button, Chip, Label, Tag } from "../DesignSystem";
import { Check } from "@phosphor-icons/react";

const manrope = Manrope({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${manrope.className}`}>
        <div
          style={{
            display: "flex",
            gap: "8px",
          }}
        >
          <Button onClick={() => {}} type="primary">
            primary
          </Button>
          <Button onClick={() => {}} type="secondary">
            secondary
          </Button>
          <Button onClick={() => {}} type="tertiary">
            tertiary
          </Button>
          <Button onClick={() => {}} type="danger">
            danger
          </Button>
        </div>
        <div
          style={{
            display: "flex",
            gap: "8px",
            marginTop: "8px",
          }}
        >
          <Tag type="success">32</Tag>
          <Tag type="info">32</Tag>
          <Tag type="danger">32</Tag>
        </div>
        <div
          style={{
            display: "flex",
            gap: "8px",
            marginTop: "8px",
          }}
        >
          <Chip type="primary" onClick={() => {}}>
            <Check /> Figma
          </Chip>
          <Chip type="secondary">Wireframes</Chip>
        </div>
        <div
          style={{
            display: "flex",
            gap: "8px",
            marginTop: "8px",
          }}
        >
          <Label type="success">Good</Label>
          <Label type="warning">Fair</Label>
          <Label type="danger">Bad</Label>
        </div>
        <div
          style={{
            display: "flex",
            gap: "8px",
            marginTop: "8px",
            maxWidth: "500px",
            flexWrap: "wrap",
          }}
        >
          <Alert onDismiss={() => {}} onUndo={() => {}} type="success">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
            has been the industry's standard dummy text ever since the 1500s, when an unknown
            printer took a galley of type and scrambled it to make a type specimen book. It has
            survived not only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
            publishing software like Aldus PageMaker including versions of Lorem Ipsum.
          </Alert>
          <Alert onDismiss={() => {}} type="danger">
            Bad
          </Alert>
        </div>
        <div id="tooltip-portal"></div>
      </main>
    </>
  );
}
